# CordBrief Core Service Dockerfile
FROM golang:alpine AS builder

WORKDIR /src
COPY go.mod ./
COPY cmd/ ./cmd/
COPY internal/ ./internal/

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /bin/cordbrief ./cmd/cordbrief

FROM alpine:3.20

RUN adduser -D -u 1000 -s /bin/sh cordbrief \
    && mkdir -p /var/cordbrief/exchange /var/cordbrief/data \
    && chown -R cordbrief:cordbrief /var/cordbrief

USER cordbrief
WORKDIR /home/cordbrief

COPY --from=builder /bin/cordbrief /usr/local/bin/cordbrief

ENV CORDBRIEF_EXCHANGE_DIR=/var/cordbrief/exchange
ENV CORDBRIEF_DATA_DIR=/var/cordbrief/data

ENTRYPOINT ["/usr/local/bin/cordbrief"]
CMD ["--help"]
